import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { PUBLIC_JSON_SCHEMA_VERSION } from '../../src/constants/public-json-schema'

const readmePath = path.resolve(__dirname, '../../README.md')
const readme = fs.readFileSync(readmePath, 'utf8')
const publicJsonSchemaDocPath = path.resolve(__dirname, '../../docs/public-json-schema.md')
const publicJsonSchemaDoc = fs.readFileSync(publicJsonSchemaDocPath, 'utf8')
const changelogPath = path.resolve(__dirname, '../../CHANGELOG.md')
const changelog = fs.readFileSync(changelogPath, 'utf8')
const releaseChecklistPath = path.resolve(__dirname, '../../docs/release-checklist.md')
const releaseChecklist = fs.readFileSync(releaseChecklistPath, 'utf8')
const machineReadableSchemaPath = path.resolve(__dirname, '../../docs/public-json-output.schema.json')
const machineReadableSchema = JSON.parse(fs.readFileSync(machineReadableSchemaPath, 'utf8')) as {
  $id?: string
  properties?: {
    schemaVersion?: {
      const?: string
    }
  }
}

describe('docs consistency', () => {
  it('README 首屏能力摘要包含 schema 命令，避免公开命令面与首页摘要漂移', () => {
    expect(readme).toContain('`preview / use / rollback / current / list / validate / export / add / schema`')
  })

  it('README 保留 smoke:release 入口与验证范围，避免公开开发入口落后于实际脚本', () => {
    expect(readme).toContain('corepack pnpm smoke:release')
    expect(readme).toContain('顶层 `--help` 可发现性')
    expect(readme).toContain('`schema --schema-version --json` 成功态 contract')
    expect(readme).toContain('`current/list --json` platformSummary contract')
    expect(readme).toContain('稳定 stderr 失败出口')
    expect(readme).toContain('稳定 `--json` 失败 envelope')
  })

  it('README / schema / changelog 对 import apply 的平台边界与批量约束保持一致', () => {
    expect(readme).toContain('`import apply` 当前支持 Gemini / Codex / Claude')
    expect(readme).toContain('`import apply <file> --profile <id>`')
    expect(readme).toContain('`import apply <file> --profiles <id1,id2,...>`')
    expect(readme).toContain('第一版批量 apply 仅支持同平台 profile')
    expect(readme).toContain('按传入顺序逐条执行')
    expect(readme).toContain('`IMPORT_APPLY_BATCH_PLATFORM_MISMATCH`')
    expect(readme).toContain('`IMPORT_APPLY_BATCH_PARTIAL_FAILURE`')
    expect(readme).toContain('Codex 不使用 `--scope`')

    expect(publicJsonSchemaDoc).toContain('当前支持 Gemini / Codex / Claude profile。')
    expect(publicJsonSchemaDoc).toContain('`--profile` 用于单条 apply，`--profiles` 用于同平台批量 apply。')
    expect(publicJsonSchemaDoc).toContain('第一版批量 apply 只支持同平台 profile，且按传入顺序逐条执行。')
    expect(publicJsonSchemaDoc).toContain('`IMPORT_APPLY_BATCH_PLATFORM_MISMATCH`')
    expect(publicJsonSchemaDoc).toContain('`IMPORT_APPLY_BATCH_PARTIAL_FAILURE`')
    expect(publicJsonSchemaDoc).toContain('Codex 不支持 `--scope`')

    expect(changelog).toContain('`import apply` 当前支持 Gemini / Codex / Claude。')
    expect(changelog).toContain('一次仅支持应用单个 imported profile')
    expect(changelog).toContain('Codex 不支持 `--scope`')
  })

  it('README / schema 文档对 reference preview/use contract 保持一致', () => {
    expect(readme).not.toContain('`preview/use/import apply` 暂不解析引用')
    expect(readme).toContain('`preview/use` 第一阶段已消费 `env://VAR_NAME` 引用')
    expect(readme).toContain('`referenceReadiness`')
    expect(readme).toContain('`referenceReadiness` 只是 `preview` 成功态的轻量汇总入口')
    expect(readme).toContain('不替代 `referenceDecision` / `referenceGovernance`')
    expect(readme).toContain('`native-reference-write`')
    expect(readme).toContain('`inline-fallback-write`')
    expect(readme).toContain('`reference-blocked`')
    expect(readme).toContain('如继续执行，将以明文写入目标配置文件。')

    expect(publicJsonSchemaDoc).toContain('`preview/use` 第一阶段已消费 `env://VAR_NAME` 引用')
    expect(publicJsonSchemaDoc).toContain('`referenceReadiness`')
    expect(publicJsonSchemaDoc).toContain('`referenceReadiness` 只是 `preview` 成功态的轻量汇总入口')
    expect(publicJsonSchemaDoc).toContain('不替代 `referenceDecision` / `referenceGovernance`')
    expect(publicJsonSchemaDoc).toContain('`native-reference-write`')
    expect(publicJsonSchemaDoc).toContain('`inline-fallback-write`')
    expect(publicJsonSchemaDoc).toContain('`reference-blocked`')
    expect(publicJsonSchemaDoc).toContain('如继续执行，将以明文写入目标配置文件。')

    expect(changelog).toContain('`preview / use` 第一阶段已消费 `env://VAR_NAME` secret reference')
  })

  it('README / schema 文档对 current/list platformSummary contract 保持一致', () => {
    expect(readme).toContain('`current --json` 会在 `detections[]` 里同时返回当前生效来源 `currentScope`、机器可消费的 `platformSummary`')
    expect(readme).toContain('`data.summary.platformStats[]` 则把每个平台的 profile 数、当前 state 记录、当前检测命中和 explainable 摘要做了一层聚合')
    expect(readme).toContain('`data.summary.referenceStats`')
    expect(readme).toContain('文本输出现在也按同一顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”')
    expect(readme).toContain('`list --json` 会在每个 profile 条目上带出所属平台的 `platformSummary`')
    expect(readme).toContain('`data.summary.platformStats[]` 会把当前返回批次里每个平台的 profile 数、当前 state 记录、当前检测命中和 explainable 摘要聚合出来')
    expect(readme).toContain('reference profile、多少条仍是 inline secret、多少条当前属于 write unsupported')
    expect(readme).toContain('`resolvedReferenceProfileCount` / `missingReferenceProfileCount` / `unsupportedReferenceProfileCount`')
    expect(readme).toContain('文本输出也与这条读取顺序对齐：先读“按平台汇总”，再读“referenceStats 摘要”')
    expect(readme).toContain('"action": "current"')
    expect(readme).toContain('"action": "list"')
    expect(readme).toContain('"platformStats": [')
    expect(readme).toContain('"code": "CLAUDE_SCOPE_PRECEDENCE"')
    expect(readme).toContain('"code": "GEMINI_SCOPE_PRECEDENCE"')
    expect(readme).toContain('"code": "CODEX_LIST_IS_PROFILE_LEVEL"')
    expect(readme).toContain('"code": "CODEX_CURRENT_REQUIRES_BOTH_FILES"')

    expect(publicJsonSchemaDoc).toContain('`current/list/validate/export/import preview/import apply` 会输出 `platformSummary`')
    expect(publicJsonSchemaDoc).toContain('文本输出也沿同一顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”')
    expect(publicJsonSchemaDoc).toContain('文本输出也与此对齐：先读“按平台汇总”，再读“referenceStats 摘要”')
    expect(publicJsonSchemaDoc).toContain('"action": "current"')
    expect(publicJsonSchemaDoc).toContain('"action": "list"')
    expect(publicJsonSchemaDoc).toContain('### JSON 示例导航')
    expect(publicJsonSchemaDoc).toContain('| Command | 适合谁读 | 成功重点字段 | 失败重点字段 / 失败码 |')
    expect(publicJsonSchemaDoc).toContain('CLI 用户、UI 接入方')
    expect(publicJsonSchemaDoc).toContain('自动化脚本、导入迁移工具')
    expect(publicJsonSchemaDoc).toContain('UI 接入方、导入迁移工具')
    expect(publicJsonSchemaDoc).toContain('推荐消费顺序：先读 `summary.platformStats[]` 和 `summary.referenceStats` 拿平台级聚合与 reference 聚合')
    expect(publicJsonSchemaDoc).toContain('推荐消费顺序：先读 `summary.platformStats[]` 和 `summary.referenceStats` 做平台分组与治理分层')
    expect(publicJsonSchemaDoc).toContain('推荐消费顺序：先读 `summary.platformStats[]` 和 `summary.referenceStats` 看平台级通过/限制聚合与 reference 聚合')
    expect(publicJsonSchemaDoc).toContain('推荐消费顺序：先读 `summary.platformStats[]`、`summary.referenceStats` 和 `summary.secretExportPolicy` 看平台级聚合与本次 secret 导出策略')
    expect(publicJsonSchemaDoc).toContain('CurrentListPlatformStat')
    expect(publicJsonSchemaDoc).toContain('SecretReferenceStats')
    expect(publicJsonSchemaDoc).toContain('resolvedReferenceProfileCount: number')
    expect(publicJsonSchemaDoc).toContain('missingReferenceProfileCount: number')
    expect(publicJsonSchemaDoc).toContain('unsupportedReferenceProfileCount: number')
    expect(publicJsonSchemaDoc).toContain('[`current --json`](#current---json)')
    expect(publicJsonSchemaDoc).toContain('[`list --json`](#list---json)')
    expect(publicJsonSchemaDoc).toContain('[`preview --json`](#preview---json)')
    expect(publicJsonSchemaDoc).toContain('[`use --json`](#use---json)')
    expect(publicJsonSchemaDoc).toContain('[`rollback --json`](#rollback---json)')
    expect(publicJsonSchemaDoc).toContain('`CONFIRMATION_REQUIRED` / `USE_FAILED`')
    expect(publicJsonSchemaDoc).toContain('`ROLLBACK_SCOPE_MISMATCH` / `ROLLBACK_FAILED`')
    expect(publicJsonSchemaDoc).toContain('`PREVIEW_FAILED`')
    expect(publicJsonSchemaDoc).toContain('system-defaults < user < project < system-overrides')
    expect(publicJsonSchemaDoc).toContain('user < project < local')
    expect(publicJsonSchemaDoc).toContain('multi-file-composition')
    expect(publicJsonSchemaDoc).toContain('GEMINI_SCOPE_PRECEDENCE')
    expect(publicJsonSchemaDoc).toContain('CLAUDE_SCOPE_PRECEDENCE')
    expect(publicJsonSchemaDoc).toContain('CODEX_MULTI_FILE_CONFIGURATION')
  })

  it('README / schema 文档对 add summary.platformStats contract 保持一致', () => {
    expect(readme).toContain('`add --json` 的 `scopeCapabilities` 在成功摘要顶层 `data`')
    expect(readme).toContain('成功态也会把 `data.summary.platformStats[]`、`data.summary.referenceStats`、`data.summary.executabilityStats` 一起暴露成稳定 summary 入口')
    expect(readme).toContain('`add` 的 secret 输入面支持两类互斥模式：明文 `--key`，或 reference-only 的 `--secret-ref` / `--auth-reference`。')
    expect(readme).toContain('`add` 只负责录入 reference 输入，不在该阶段解析当前环境能否执行。')
    expect(readme).toContain('若既没有 key 也没有 reference，失败码为 `ADD_INPUT_REQUIRED`；若同时传入明文 key 与 reference，失败码为 `ADD_INPUT_CONFLICT`。')
    expect(readme).toContain('文本输出也按这个顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”和“executabilityStats 摘要”，最后进入 add 细节：')
    expect(readme).toContain('"action": "add"')
    expect(readme).toContain('"platformStats": [')
    expect(readme).toContain('"code": "CLAUDE_SCOPE_PRECEDENCE"')

    expect(publicJsonSchemaDoc).toContain('### add --json')
    expect(publicJsonSchemaDoc).toContain('`data.summary.platformStats[]` 是 add 成功态的单平台聚合入口')
    expect(publicJsonSchemaDoc).toContain('`data.summary.referenceStats` 会补出当前新增 profile 的 secret/reference 形态聚合')
    expect(publicJsonSchemaDoc).toContain('`add` 的 secret 输入面支持两类互斥模式：明文 `--key`，或 reference-only 的 `--secret-ref` / `--auth-reference`。')
    expect(publicJsonSchemaDoc).toContain('`add` 只负责录入 reference 输入，不在该阶段解析当前环境能否执行；真正的本地解析、治理判断和写入可执行性检查留在 `preview/use/import apply`。')
    expect(publicJsonSchemaDoc).toContain('若既没有 key 也没有 reference，失败码为 `ADD_INPUT_REQUIRED`；若同时传入明文 key 与 reference，失败码为 `ADD_INPUT_CONFLICT`。')
    expect(publicJsonSchemaDoc).toContain('文本输出也按这条顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”和“executabilityStats 摘要”，最后进入 add 细节。')
    expect(publicJsonSchemaDoc).toContain('platformStats?: SinglePlatformStat[]')
    expect(publicJsonSchemaDoc).toContain('referenceStats?: SecretReferenceStats')
    expect(publicJsonSchemaDoc).toContain('executabilityStats?: ExecutabilityStats')
  })

  it('schema 文档保留公共 explainable 字段总览，避免四个命令的共享字段语义漂移', () => {
    expect(publicJsonSchemaDoc).toContain('## Common Explainable Fields')
    expect(publicJsonSchemaDoc).toContain('### `platformSummary`')
    expect(publicJsonSchemaDoc).toContain('### `scopeCapabilities`')
    expect(publicJsonSchemaDoc).toContain('### `scopeAvailability`')
    expect(publicJsonSchemaDoc).toContain('### `defaultWriteScope`')
    expect(publicJsonSchemaDoc).toContain('### `observedAt`')
    expect(publicJsonSchemaDoc).toContain('### Field Presence Matrix')
    expect(publicJsonSchemaDoc).toContain('| `platformSummary` | yes | yes | yes | yes | yes | yes |')
    expect(publicJsonSchemaDoc).toContain('| `scopeAvailability` | yes | yes | no | yes | via observation | conditional |')
    expect(publicJsonSchemaDoc).toContain('| `observedAt` | no | no | no | yes | via observation | no |')
  })

  it('schema 文档保留跨命令字段对齐边界，避免 import 线与只读命令线继续长出近义 contract', () => {
    expect(publicJsonSchemaDoc).toContain('## Cross-Command Alignment')
    expect(publicJsonSchemaDoc).toContain('### Stable Shared Fields')
    expect(publicJsonSchemaDoc).toContain('### Stable Import-Only Fields')
    expect(publicJsonSchemaDoc).toContain('### Action-Specific Stable Fields')
    expect(publicJsonSchemaDoc).toContain('### Adapter-Private Or Expandable Fields')
    expect(publicJsonSchemaDoc).toContain('| `platformSummary` | `current` / `list` / `validate` / `export` / `import preview` / `import apply` |')
    expect(publicJsonSchemaDoc).toContain('| `exportedObservation` | `import preview` / `import apply` failure details |')
    expect(publicJsonSchemaDoc).toContain('| `scopePolicy` | `preview` / `use` / `rollback` / `import apply` |')
    expect(publicJsonSchemaDoc).toContain('- `effectiveConfig`')
    expect(publicJsonSchemaDoc).toContain('应继续沿用 `exportedObservation` / `localObservation` / `fidelity`')
  })

  it('README / schema 文档对 import preview/apply platformSummary contract 保持一致', () => {
    expect(readme).toContain('`import --json` 会在每个 item 上带出所属平台的 `platformSummary`')
    expect(readme).toContain('`import apply --json` 成功态也会返回 `platformSummary`')
    expect(readme).toContain('`import apply --json` 成功态会把 `data.summary.platformStats[]`、`data.summary.referenceStats`、`data.summary.executabilityStats` 一起暴露成稳定 summary 入口')
    expect(readme).toContain('`import apply --dry-run --json` 会执行完整 apply 前检查')
    expect(readme).toContain('`data.dryRun=true`')
    expect(readme).toContain('`changedFiles=[]`、`noChanges=true`')
    expect(readme).toContain('下面是一份 Codex `import apply --dry-run --json` 成功样例')
    expect(readme).toContain('api-switcher import apply E:/tmp/exported-codex.json --profile codex-prod --force --dry-run --json')
    expect(readme).toContain('这个 dry-run 样例里没有 `backupId`')
    expect(readme).toContain('应读取 `data.preview.diffSummary[]`')
    expect(readme).toContain('"code": "GEMINI_SCOPE_PRECEDENCE"')
    expect(readme).toContain('"code": "CODEX_LIST_IS_PROFILE_LEVEL"')
    expect(readme).toContain('"code": "CLAUDE_SCOPE_PRECEDENCE"')
    expect(readme).toContain('[import-apply] 失败')
    expect(readme).toContain('reference 解析摘要:')
    expect(readme).toContain('sessionToken -> keychain://claude/session-token')
    expect(readme).toContain('下面是一份 Codex `import apply --profiles --json` 批量成功样例')
    expect(readme).toContain('api-switcher import apply E:/tmp/exported-codex.json --profiles codex-prod-a,codex-prod-b --force --json')
    expect(readme).toContain('"code": "IMPORT_APPLY_BATCH_PARTIAL_FAILURE"')
    expect(readme).toContain('"totalProfiles": 2')
    expect(readme).toContain('"appliedCount": 1')
    expect(readme).toContain('"failedCount": 1')

    expect(publicJsonSchemaDoc).toContain('[`import preview --json`](#import-preview---json)')
    expect(publicJsonSchemaDoc).toContain('[`import apply --json`](#import-apply---json)')
    expect(publicJsonSchemaDoc).toContain('`platformSummary`、`summary.platformStats`、`summary.referenceStats`、`summary.executabilityStats`、`scopePolicy`、`preview`、`dryRun`、`backupId`、`changedFiles`')
    expect(publicJsonSchemaDoc).toContain('`--dry-run` 会执行同一套 apply 前检查')
    expect(publicJsonSchemaDoc).toContain('`dryRun=true` 表示本次只执行 apply 前检查')
    expect(publicJsonSchemaDoc).toContain('backupId?: string')
    expect(publicJsonSchemaDoc).toContain('Codex `import apply --dry-run --json` 成功样例：')
    expect(publicJsonSchemaDoc).toContain('"dryRun": true')
    expect(publicJsonSchemaDoc).toContain('"backupCreated": false')
    expect(publicJsonSchemaDoc).toContain('`preview.diffSummary[]` 仍保留 planned diff')
    expect(publicJsonSchemaDoc).toContain('`CONFIRMATION_REQUIRED` / scope unavailable 类失败')
    expect(publicJsonSchemaDoc).toContain('platformSummary?: PlatformExplainableSummary')
    expect(publicJsonSchemaDoc).toContain('`platformSummary` 是 item 级稳定平台摘要')
    expect(publicJsonSchemaDoc).toContain('`platformSummary` 是 success payload 上的平台摘要')
    expect(publicJsonSchemaDoc).toContain('### import apply --json')
    expect(publicJsonSchemaDoc).toContain('成功样例：')
    expect(publicJsonSchemaDoc).toContain('失败样例：')
    expect(publicJsonSchemaDoc).toContain('失败样例重点看 `CONFIRMATION_REQUIRED` 或 scope unavailable 类失败下的 `referenceGovernance`')
    expect(publicJsonSchemaDoc).toContain('`referenceGovernance` 是失败态的治理类索引')
    expect(publicJsonSchemaDoc).toContain('`error.details.referenceGovernance.referenceDetails[]`')
    expect(publicJsonSchemaDoc).toContain('REFERENCE_ENV_UNRESOLVED')
    expect(publicJsonSchemaDoc).toContain('REFERENCE_SCHEME_UNSUPPORTED')
    expect(publicJsonSchemaDoc).toContain('"action": "import-apply"')
    expect(publicJsonSchemaDoc).toContain('"code": "CONFIRMATION_REQUIRED"')
    expect(publicJsonSchemaDoc).toContain('"code": "CODEX_LIST_IS_PROFILE_LEVEL"')
    expect(publicJsonSchemaDoc).toContain('"code": "CLAUDE_SCOPE_PRECEDENCE"')
    expect(publicJsonSchemaDoc).toContain('Codex `import apply --profiles --json` 批量成功样例：')
    expect(publicJsonSchemaDoc).toContain('api-switcher import apply E:/tmp/exported-codex.json --profiles codex-prod-a,codex-prod-b --force --json')
    expect(publicJsonSchemaDoc).toContain('批量部分失败样例：')
    expect(publicJsonSchemaDoc).toContain('"code": "IMPORT_APPLY_BATCH_PARTIAL_FAILURE"')
    expect(publicJsonSchemaDoc).toContain('"totalProfiles": 2')
    expect(publicJsonSchemaDoc).toContain('"appliedCount": 1')
    expect(publicJsonSchemaDoc).toContain('"failedCount": 1')
  })

  it('README / schema 文档对 schema --json --action import-apply 的批量失败 discoverability 样例保持一致', () => {
    expect(readme).toContain('"action": "import-apply"')
    expect(readme).toContain('"path": "error.details.results[].failureCategory"')
    expect(readme).toContain('"path": "error.details.results[].reasonCodes"')
    expect(readme).toContain('"conditionCode": "WHEN_BATCH_PARTIAL_FAILURE_RESULTS_ARE_EMITTED"')
    expect(readme).toContain('"path": "error.details.results[].failureCategory", "semantic": "error-details"')
    expect(readme).toContain('"path": "error.details.results[].reasonCodes", "semantic": "error-details"')

    expect(publicJsonSchemaDoc).toContain('"action": "import-apply"')
    expect(publicJsonSchemaDoc).toContain('"path": "error.details.results[].failureCategory"')
    expect(publicJsonSchemaDoc).toContain('"path": "error.details.results[].reasonCodes"')
    expect(publicJsonSchemaDoc).toContain('"conditionCode": "WHEN_BATCH_PARTIAL_FAILURE_RESULTS_ARE_EMITTED"')
    expect(publicJsonSchemaDoc).toContain('"path": "error.details.results[].failureCategory", "semantic": "error-details"')
    expect(publicJsonSchemaDoc).toContain('"path": "error.details.results[].reasonCodes", "semantic": "error-details"')
    expect(readme).toContain('"primaryErrorFields": ["error.code", "error.message", "error.details.results[].failureCategory", "error.details.results[].reasonCodes"]')
    expect(readme).toContain('"stage": "error-core", "fields": ["error.code", "error.message"]')
    expect(readme).toContain('"stage": "error-details", "fields": ["error.details.results[].failureCategory", "error.details.results[].reasonCodes"]')

    expect(publicJsonSchemaDoc).toContain('"primaryErrorFields": ["error.code", "error.message", "error.details.results[].failureCategory", "error.details.results[].reasonCodes"]')
    expect(publicJsonSchemaDoc).toContain('"stage": "error-core", "fields": ["error.code", "error.message"]')
    expect(publicJsonSchemaDoc).toContain('"stage": "error-details", "fields": ["error.details.results[].failureCategory", "error.details.results[].reasonCodes"]')
  })

  it('README / schema 文档在 schema --json 完整 catalog 大样例区域也显式提到 import-apply 的批量失败读取顺序', () => {
    expect(readme).toContain('完整 `commandCatalog.actions[]` 大样例里，`import-apply` 也会沿用同一组批量失败入口：')
    expect(readme).toContain('`primaryErrorFields` 先暴露 `error.code / error.message / error.details.results[].failureCategory / error.details.results[].reasonCodes`')
    expect(readme).toContain('`readOrderGroups.failure` 再固定为 `error-core -> error-details`')

    expect(publicJsonSchemaDoc).toContain('完整 `commandCatalog.actions[]` 大样例里，`import-apply` 也会沿用同一组批量失败入口：')
    expect(publicJsonSchemaDoc).toContain('`primaryErrorFields` 先暴露 `error.code / error.message / error.details.results[].failureCategory / error.details.results[].reasonCodes`')
    expect(publicJsonSchemaDoc).toContain('`readOrderGroups.failure` 再固定为 `error-core -> error-details`')
  })

  it('README / schema 文档对 use/rollback platformSummary contract 保持一致', () => {
    expect(readme).toContain('`use --json` 成功时除了 `scopeCapabilities` 与 `scopeAvailability`，还会返回 `platformSummary`')
    expect(readme).toContain('`use --dry-run --json` 会执行同一套写入前检查')
    expect(readme).toContain('计划差异仍保留在 `data.preview.diffSummary[]`')
    expect(readme).toContain('下面是一份 Gemini `use --dry-run --json` 成功样例')
    expect(readme).toContain('api-switcher use gemini-prod --scope project --force --dry-run --json')
    expect(readme).toContain('这个 dry-run 样例里没有 `backupId`')
    expect(readme).toContain('`rollback --json` 成功时也会返回 `platformSummary`')
    expect(readme).toContain('"action": "use"')
    expect(readme).toContain('"action": "rollback"')
    expect(readme).toContain('"code": "GEMINI_SCOPE_PRECEDENCE"')
    expect(readme).toContain('"code": "CODEX_MULTI_FILE_CONFIGURATION"')
    expect(readme).toContain('[use] 失败')
    expect(readme).toContain('secondaryApiKey -> env://GEMINI_SECONDARY_API_KEY')

    expect(publicJsonSchemaDoc).toContain('成功时，`data.platformSummary` 会把平台 precedence 或多文件组合语义一起返回。')
    expect(publicJsonSchemaDoc).toContain('成功时，`data.platformSummary` 会把恢复目标所属平台的 explainable 摘要一起返回。')
    expect(readme).toContain('单平台命令也统一提供 `data.summary.platformStats[]`')
    expect(readme).toContain('`use --json` 成功时除了 `scopeCapabilities` 与 `scopeAvailability`，还会返回 `platformSummary`。同时，`data.summary.platformStats[]`、`data.summary.referenceStats`、`data.summary.executabilityStats` 也会一起给出稳定 summary 入口。')
    expect(readme).toContain('`rollback --json` 成功时也会返回 `platformSummary`。同时，`data.summary.platformStats[]`、`data.summary.referenceStats`、`data.summary.executabilityStats` 也会一起给出稳定 summary 入口。')
    expect(publicJsonSchemaDoc).toContain('`data.summary.platformStats[]` 是成功态的单平台聚合入口')
    expect(publicJsonSchemaDoc).toContain('`platformSummary`、`summary.platformStats`、`summary.referenceStats`、`summary.executabilityStats`、`scopeCapabilities`、`scopeAvailability`、`dryRun`、`changedFiles`、`backupId`')
    expect(publicJsonSchemaDoc).toContain('`use --dry-run --json` 与 `import apply --dry-run --json` 保持同一 execution contract')
    expect(publicJsonSchemaDoc).toContain('Gemini `use --dry-run --json` 成功样例：')
    expect(publicJsonSchemaDoc).toContain('"dryRun": true')
    expect(publicJsonSchemaDoc).toContain('"backupCreated": false')
    expect(publicJsonSchemaDoc).toContain('`platformSummary`、`summary.platformStats`、`summary.referenceStats`、`summary.executabilityStats`、`scopePolicy`、`scopeCapabilities`、`scopeAvailability`、`restoredFiles`')
    expect(publicJsonSchemaDoc).toContain('`scopePolicy`、`scopeCapabilities`、`scopeAvailability`、`ROLLBACK_SCOPE_MISMATCH` / `ROLLBACK_FAILED`')
    expect(publicJsonSchemaDoc).toContain('platformSummary?: PlatformExplainableSummary')
    expect(publicJsonSchemaDoc).toContain('完整 JSON 样例见 [`README.md`](../README.md) 中的 `use --json` 成功/失败示例。')
    expect(publicJsonSchemaDoc).toContain('完整 JSON 样例见 [`README.md`](../README.md) 中的 `rollback --json` 成功/失败示例。')
    expect(publicJsonSchemaDoc).toContain('成功样例：')
    expect(publicJsonSchemaDoc).toContain('失败样例：')
    expect(publicJsonSchemaDoc).toContain('样例阅读方式：')
    expect(publicJsonSchemaDoc).toContain('成功样例重点看 success payload')
    expect(publicJsonSchemaDoc).toContain('失败样例重点看 `CONFIRMATION_REQUIRED` 下的 `referenceGovernance`')
    expect(publicJsonSchemaDoc).toContain('referenceGovernance?: ReferenceGovernanceFailureDetails')
    expect(publicJsonSchemaDoc).toContain('referenceDetails?: ReferenceGovernanceDetail[]')
    expect(publicJsonSchemaDoc).toContain('"primaryReason": "INLINE_SECRET_PRESENT"')
    expect(publicJsonSchemaDoc).toContain('"reasonCodes": [')
    expect(publicJsonSchemaDoc).toContain('"code": "REFERENCE_ENV_RESOLVED"')
    expect(publicJsonSchemaDoc).toContain('"action": "use"')
    expect(publicJsonSchemaDoc).toContain('"action": "rollback"')
    expect(publicJsonSchemaDoc).toContain('"backupId": "snapshot-gemini-001"')
    expect(publicJsonSchemaDoc).toContain('"code": "GEMINI_SCOPE_PRECEDENCE"')
    expect(publicJsonSchemaDoc).toContain('"code": "CONFIRMATION_REQUIRED"')
    expect(publicJsonSchemaDoc).toContain('"code": "ROLLBACK_SCOPE_MISMATCH"')
  })

  it('schema 文档为 preview/import apply 保留成功与失败样例标题，避免顶部导航指向后正文仍不对称', () => {
    expect(publicJsonSchemaDoc).toContain('### preview --json')
    expect(readme).toContain('成功时也会返回 `scopePolicy`')
    expect(readme).toContain('成功态同样会补齐 `data.summary.referenceStats` 与 `data.summary.executabilityStats`')
    expect(readme).toContain('文本输出也按这个顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”和“executabilityStats 摘要”，最后进入 preview 细节。')
    expect(publicJsonSchemaDoc).toContain('`data.scopePolicy` 描述本次预览请求的目标 scope 语义')
    expect(publicJsonSchemaDoc).toContain('`data.summary.referenceStats` 会补出当前写入 profile 的 secret/reference 形态聚合')
    expect(publicJsonSchemaDoc).toContain('文本输出也按这条顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”和“executabilityStats 摘要”，最后进入 preview 细节。')
    expect(publicJsonSchemaDoc).toContain('scopePolicy?: SnapshotScopePolicy')
    expect(publicJsonSchemaDoc).toContain('如果是 blocked reference，请优先在成功样例里读取 `data.referenceDecision` 与 `data.referenceGovernance`')
    expect(publicJsonSchemaDoc).toContain('"action": "preview"')
    expect(publicJsonSchemaDoc).toContain('"requestedScope": "project"')
    expect(publicJsonSchemaDoc).toContain('"writeDecision": "reference-blocked"')
    expect(publicJsonSchemaDoc).toContain('### import apply --json')
    expect(readme).toContain('`import apply --json` 成功态会把 `data.summary.platformStats[]`、`data.summary.referenceStats`、`data.summary.executabilityStats` 一起暴露成稳定 summary 入口')
    expect(publicJsonSchemaDoc).toContain('`summary.platformStats[]` 是 success payload 上的单平台聚合入口')
    expect(publicJsonSchemaDoc).toContain('失败样例重点看 `CONFIRMATION_REQUIRED` 或 scope unavailable 类失败下的 `referenceGovernance`')
    expect(publicJsonSchemaDoc).toContain('"action": "import-apply"')
    expect(publicJsonSchemaDoc).toContain('"code": "CONFIRMATION_REQUIRED"')
  })

  it('README / schema 文档对 validate/export platformSummary contract 保持一致', () => {
    expect(readme).toContain('`validate --json` 与 `export --json` 也是按条目输出 `platformSummary`')
    expect(readme).toContain('`data.summary.platformStats[]` 会把当前返回批次里每个平台的 profile 数、校验通过数、warnings/limitations 总数和平台 explainable 摘要聚合出来')
    expect(readme).toContain('`data.summary.referenceStats` 则补出当前批次的 reference / inline / write unsupported 聚合')
    expect(readme).toContain('并额外区分 `env://` 可解析、缺失和暂不支持 scheme 的 reference profile')
    expect(readme).toContain('文本输出也按这条 schema catalog 顺序组织：先看“按平台汇总”，再看“referenceStats 摘要”')
    expect(readme).toContain('"code": "CLAUDE_SCOPE_PRECEDENCE"')
    expect(readme).toContain('"okCount": 1')

    expect(publicJsonSchemaDoc).toContain('`validate` 的每个 item 会带出对应 profile 平台的 `platformSummary`')
    expect(publicJsonSchemaDoc).toContain('`export` 的每个导出 profile 条目会带出所属平台的 `platformSummary`')
    expect(publicJsonSchemaDoc).toContain('`summary.platformStats[]` 提供当前校验批次的 platform-aware 聚合')
    expect(publicJsonSchemaDoc).toContain('`summary.platformStats[]` 把当前导出批次按平台聚合')
    expect(publicJsonSchemaDoc).toContain('`summary.referenceStats` 则补充当前校验批次里 reference / inline / write unsupported 的治理摘要')
    expect(publicJsonSchemaDoc).toContain('`summary.referenceStats` 则补出本次导出里 reference / inline / write unsupported 的批次聚合')
    expect(publicJsonSchemaDoc).toContain('文本输出同样先给出“按平台汇总”和“referenceStats 摘要”')
    expect(publicJsonSchemaDoc).toContain('文本输出也采用同一顺序：先看“按平台汇总”，再看“referenceStats 摘要”')
    expect(publicJsonSchemaDoc).toContain('[`validate --json`](#validate---json)')
    expect(publicJsonSchemaDoc).toContain('[`export --json`](#export---json)')
    expect(publicJsonSchemaDoc).toContain('platformSummary?: PlatformExplainableSummary')
    expect(publicJsonSchemaDoc).toContain('ValidateExportPlatformStat')
  })

  it('CHANGELOG 首版能力摘要包含 schema 命令，避免 release note 与 README 首页命令面漂移', () => {
    expect(changelog).toContain('`add / list / current / validate / preview / use / rollback / export / schema`')
  })

  it('CHANGELOG 记录当前 release smoke 护栏能力，避免自动化演进只落在脚本里', () => {
    expect(changelog).toContain('`smoke:release` 现在会校验 `dist` 构建产物的顶层 `--help` 关键命令面')
    expect(changelog).toContain('`schema --schema-version --json` 成功态 contract')
    expect(changelog).toContain('未知命令保持 Commander `stderr` 失败行为')
    expect(changelog).toContain('`import <missing-file> --json` 返回 `schemaVersion / ok=false / action / error.code`')
  })

  it('release checklist 保留 smoke:release 发布前入口，避免自动化基线文档漂移', () => {
    expect(releaseChecklist).toContain('corepack pnpm smoke:release')
    expect(releaseChecklist).toContain('发布前一键 smoke 入口')
    expect(releaseChecklist).toContain('CLI help / schema --json')
    expect(releaseChecklist).toContain('schema --schema-version --json')
    expect(releaseChecklist).toContain('schema --json --consumer-profile readonly-import-batch')
    expect(releaseChecklist).toContain('schema --json --action import-apply')
    expect(releaseChecklist).toContain('schema --json --recommended-action continue-to-write')
    expect(releaseChecklist).toContain('schema --json --catalog-summary')
    expect(releaseChecklist).toContain('`dist` 构建产物')
    expect(releaseChecklist).toContain('当前公开 contract')
    expect(releaseChecklist).toContain('可发现性')
    expect(releaseChecklist).toContain('顶层 `--help` 仍保留关键命令面')
    expect(releaseChecklist).toContain('preview / use / rollback / current / list / validate / export / add / schema / import')
    expect(releaseChecklist).toContain('current/list --json')
    expect(releaseChecklist).toContain('platformSummary')
    expect(releaseChecklist).toContain('scope-precedence')
    expect(releaseChecklist).toContain('multi-file-composition')
    expect(releaseChecklist).toContain('未知命令仍保持稳定的 Commander 失败出口')
    expect(releaseChecklist).toContain('exit code `1`')
    expect(releaseChecklist).toContain('stderr` 含 `unknown command`')
    expect(releaseChecklist).toContain('JSON 失败态')
    expect(releaseChecklist).toContain('import <missing-file> --json')
    expect(releaseChecklist).toContain('schemaVersion / ok=false / action / error.code')
  })

  it('schema 文档示例与源码常量、machine-readable schema 的版本和 schemaId 保持一致', () => {
    expect(machineReadableSchema.properties?.schemaVersion?.const).toBe(PUBLIC_JSON_SCHEMA_VERSION)

    expect(publicJsonSchemaDoc).toContain(`schemaVersion: '${PUBLIC_JSON_SCHEMA_VERSION}'`)
    expect(publicJsonSchemaDoc).toContain(`schemaId: '${machineReadableSchema.$id}'`)
  })

  it('README 保留 schema --json 最小公开元字段示例，避免示例与真实 contract 漂移', () => {
    expect(readme).toContain('"action": "schema"')
    expect(readme).toContain(`"schemaVersion": "${PUBLIC_JSON_SCHEMA_VERSION}"`)
    expect(readme).toContain(`"schemaId": "${machineReadableSchema.$id}"`)
    expect(readme).toContain('"commandCatalog": {')
    expect(readme).toContain('"hasPlatformStats": true')
    expect(readme).toContain('"primaryFields": [')
    expect(readme).toContain('"primaryErrorFields": [')
    expect(readme).toContain('"error.details.referenceGovernance"')
    expect(readme).toContain('"conditionCode": "WHEN_REFERENCE_GOVERNANCE_FAILURE_IS_DETECTED"')
    expect(readme).toContain('"semantic": "reference-governance"')
    expect(readme).toContain('"referenceGovernanceCodes": [')
    expect(readme).toContain('"code": "REFERENCE_INPUT_CONFLICT"')
    expect(readme).toContain('"recommendedHandling": "migrate-inline-secret"')
    expect(readme).toContain('失败态不要从 `summary.referenceStats` 推断治理原因')
    expect(readme).toContain('`error.details.referenceGovernance.primaryReason/reasonCodes`')
    expect(readme).toContain('`error.details.referenceGovernance.referenceDetails[]`')
    expect(readme).toContain('"code": "REFERENCE_ENV_UNRESOLVED"')
    expect(readme).toContain('"code": "REFERENCE_SCHEME_UNSUPPORTED"')
    expect(readme).toContain('"failureCodes": [')
    expect(readme).toContain('"recommendedHandling": "confirm-before-write"')
    expect(readme).toContain('"fieldPresence": [')
    expect(readme).toContain('"fieldSources": [')
    expect(readme).toContain('"fieldStability": [')
    expect(readme).toContain('"source": "schema-service"')
    expect(readme).toContain('"stabilityTier": "stable"')
    expect(readme).toContain('"stabilityTier": "bounded"')
    expect(readme).toContain('"presence": "conditional"')
    expect(readme).toContain('"conditionCode": "WHEN_SCHEMA_DOCUMENT_IS_REQUESTED"')
    expect(readme).toContain('"readOrderGroups": {')
    expect(readme).toContain('"stage": "summary"')
    expect(readme).toContain('"stage": "error-core"')
    expect(readme).toContain('"primaryFieldSemantics": [')
    expect(readme).toContain('"primaryErrorFieldSemantics": [')
    expect(readme).toContain('"summary.platformStats"')
    expect(readme).toContain('"summary.referenceStats"')
    expect(readme).toContain('`data.commandCatalog.consumerProfiles[]` 又补了一层更高阶的共享消费画像')
    expect(readme).toContain('`readonly-state-audit` 负责 `current / list / validate / export` 这类只读状态审计面')
    expect(readme).toContain('`readonly-import-batch` 负责 `import / import preview` 这类只读批量导入分析面')
    expect(readme).toContain('`sharedItemFields` 和 `optionalItemFields`')
    expect(readme).toContain('`sharedFailureFields / optionalFailureFields`')
    expect(readme).toContain('`summarySectionGuidance`，直接回答“同一套 summary section 更适合 overview、governance、gating 还是 routing”')
    expect(readme).toContain('`followUpHints` 则继续回答“summary 看完之后下一步该展开哪些 detail 字段，或者该走哪种处理动作”')
    expect(readme).toContain('`triageBuckets` 则把 summary 和 item explainable 再聚成稳定分流桶')
    expect(readme).toContain('运行时结果里的 `summary.triageStats` 则会把这些分流桶真正实例化成当前批次的计数结果')
    expect(readme).toContain('`consumerActions`，把 `summarySections / triageBuckets / followUpHints` 收口成可直接消费的动作目录')
    expect(readme).toContain('`starterTemplate`，把 `summary / items / failure / flow` 这四层最小消费骨架直接打包给调用方')
    expect(readme).toContain('`starterRecipes`，把 `discover / action / nextStep / runtime` 这组最小命令跳转 recipe 稳定挂到画像上')
    expect(readme).toContain('`defaultConsumerActionId`、`defaultCommandExample` 和 `defaultCommandPurpose`')
    expect(readme).toContain('`api-switcher current --json`')
    expect(readme).toContain('`api-switcher import <file> --json`')
    expect(readme).toContain('`readonly-state-audit-minimal-reader`')
    expect(readme).toContain('`readonly-import-batch-minimal-reader`')
    expect(readme).toContain('`commandCatalog.recommendedActions[]` 也公开了一套跨只读引导和失败恢复共用的稳定动作词表')
    expect(readme).toContain('`exampleActions` 与 `bestEntryAction`')
    expect(readme).toContain('最小消费顺序可以固定为：先从 `data.commandCatalog.consumerProfiles[]` 里选中目标画像')
    expect(readme).toContain('再读取 `bestEntryAction` 找一条最适合对齐样例的代表命令')
    expect(readme).toContain('按 `sharedSummaryFields -> sharedItemFields -> sharedFailureFields` 建立默认读取骨架')
    expect(readme).toContain('对只读画像，还可以直接读取 `summarySectionGuidance[]` 判断哪一段 summary 更适合 overview、governance、gating 或 routing')
    expect(readme).toContain('再读取 `followUpHints[]` 判断 summary 看完后下一步该展开哪些字段')
    expect(readme).toContain('如果要做更自动化的分流，还可以直接读取 `triageBuckets[]`')
    expect(readme).toContain('如果想直接拿“动作级”入口而不自己拼接这些 guidance，则直接消费 `consumerActions[]`')
    expect(readme).toContain('可以优先读取 `starterTemplate`')
    expect(readme).toContain('`starterTemplate?.summary.fields`')
    expect(readme).toContain('`starterTemplate?.items.sharedFields`')
    expect(readme).toContain('`starterTemplate?.failure.fields`')
    expect(readme).toContain('`starterTemplate?.flow.defaultConsumerFlowId`')
    expect(readme).toContain('如果你的接入层只想拿“默认第一跳”')
    expect(readme).toContain('actionId: profile?.defaultConsumerActionId')
    expect(readme).toContain('command: profile?.defaultCommandExample')
    expect(readme).toContain('purpose: profile?.defaultCommandPurpose')
    expect(readme).toContain('可以直接消费 `starterRecipes`')
    expect(readme).toContain('profile?.starterRecipes ?? []')
    expect(readme).toContain('discover: recipe.discover')
    expect(readme).toContain('runtime: recipe.runtime')
    expect(readme).toContain('只读画像的最轻量入口现在可以理解为 `defaultCommandExample -> defaultConsumerFlowId -> consumerFlow[] -> consumerActions[] -> recommendedActions[]`')
    expect(readme).toContain('const defaultReadonlyConsumerPath = {')
    expect(readme).toContain('nextStepFamily: defaultRecommendedAction?.family')
    expect(readme).toContain('api-switcher schema --json --consumer-profile readonly-import-batch')
    expect(readme).toContain('`SCHEMA_CONSUMER_PROFILE_NOT_FOUND`')
    expect(readme).toContain('api-switcher schema --json --action import-apply')
    expect(readme).toContain('"action": "use"')
    expect(readme).toContain('"conditionCode": "WHEN_DRY_RUN_IS_REQUESTED"')
    expect(readme).toContain('"fields": ["dryRun", "changedFiles", "backupId"]')
    expect(readme).toContain('`SCHEMA_ACTION_NOT_FOUND`')
    expect(readme).toContain('api-switcher schema --json --recommended-action continue-to-write')
    expect(readme).toContain('"code": "continue-to-write"')
    expect(readme).toContain('"family": "execute"')
    expect(readme).toContain('"availability": ["readonly"]')
    expect(readme).toContain('继续进入后续写入链路')
    expect(readme).toContain('`SCHEMA_RECOMMENDED_ACTION_NOT_FOUND`')
    expect(readme).toContain('api-switcher schema --json --catalog-summary')
    expect(readme).toContain('`data.catalogSummary`')
    expect(readme).toContain('`hasStarterTemplate`、`starterTemplateId`、`recommendedEntryMode`')
    expect(readme).toContain('`defaultConsumerActionId`、`defaultCommandExample`、`defaultCommandPurpose`')
    expect(readme).toContain('不再展开完整 `commandCatalog`、`schemaId` 或 `schema`')
    expect(readme).toContain('推荐的最小发现顺序是：先用 `schema --json --catalog-summary`')
    expect(readme).toContain('再按需切到完整 `schema --json`')
    expect(readme).toContain('`--catalog-summary` 的最小成功样例：')
    expect(readme).toContain('"catalogSummary": {')
    expect(readme).toContain('"consumerProfiles": 3')
    expect(readme).toContain('"recommendedActions": 15')
    expect(readme).toContain('"id": "readonly-state-audit"')
    expect(readme).toContain('"bestEntryAction": "current"')
    expect(readme).toContain('"defaultConsumerActionId": "inspect-overview"')
    expect(readme).toContain('"defaultCommandExample": "api-switcher current --json"')
    expect(readme).toContain('"recommendedEntryMode": "starter-template"')
    expect(readme).toContain('"hasStarterTemplate": true')
    expect(readme).toContain('"starterTemplateId": "readonly-state-audit-minimal-reader"')
    expect(readme).toContain('非 JSON 模式下，`schema --catalog-summary` 也会输出同一组推荐入口提示')
    expect(readme).toContain('Catalog Summary:')
    expect(readme).toContain('recommended=starter-template')
    expect(readme).toContain('recommended=full-consumer-profile')
    expect(readme).toContain('defaultAction=inspect-overview')
    expect(readme).toContain('command=api-switcher current --json')
    expect(readme).toContain('next=api-switcher schema --json --consumer-profile readonly-state-audit')
    expect(readme).toContain('api-switcher schema --json --action preview')
    expect(readme).toContain('api-switcher schema --json --recommended-action continue-to-write')
    expect(readme).toContain('catalog-summary -> action -> recommended-action -> runtime payload')
    expect(readme).toContain('"recipeId": "single-platform-write-preview-to-execute"')
    expect(readme).toContain('"discover": "api-switcher schema --json --catalog-summary"')
    expect(readme).toContain('"runtime": "api-switcher preview <selector> --json"')
    expect(readme).toContain('"code": "continue-to-write"')
    expect(readme).toContain('const consumerActions = profile?.consumerActions ?? []')
    expect(readme).toContain('const recommendedActions = schema.data.commandCatalog.recommendedActions ?? []')
    expect(readme).toContain('`summary.secretExportPolicy`')
    expect(readme).toContain('`profiles[].secretExportSummary`')
    expect(readme).toContain('"error.code"')
    expect(readme).toContain('"CONFIRMATION_REQUIRED"')
    expect(readme).toContain('"priority":')
    expect(readme).toContain('"category": "confirmation"')
    expect(readme).toContain('`failureTextActions[]` 则进一步把这层“文本入口”收口成稳定动作分组')
    expect(readme).toContain('同一个 `textEntryPoint` 可以合法出现多条记录')
    expect(readme).toContain('`successTextEntries[]`')
    expect(readme).toContain('`referenceReadiness` 在非 JSON 文本模式下优先对应 `reference-stats-summary`')
    expect(readme).toContain('`summary.platformStats` 当前优先对应 `platform-summary`')
    expect(readme).toContain('`summary.referenceStats` 当前优先对应 `reference-stats-summary`')
    expect(readme).toContain('`summary.executabilityStats` 当前优先对应 `executability-stats-summary`')
    expect(readme).toContain('`use` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(readme).toContain('`use` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(readme).toContain('`use` 的 `preview` 当前优先对应 `preview-detail`')
    expect(readme).toContain('`rollback` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(readme).toContain('`rollback` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(readme).toContain('`import apply` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(readme).toContain('`import apply` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(readme).toContain('`import apply` 的 `preview` 当前优先对应 `preview-detail`')
    expect(readme).toContain('如果你的接入层想直接拿“失败恢复消费模板”')
    expect(readme).toContain('const failureTemplate = {')
    expect(readme).toContain('byTextEntryPoint: new Map<string, string[]>()')
    expect(readme).toContain('先用 `failureCodes[].textEntryPoint` 找“该看哪段文本”')
    expect(publicJsonSchemaDoc).toContain('recommendedHandling')
    expect(publicJsonSchemaDoc).toContain('`confirm-before-write`')
    expect(publicJsonSchemaDoc).toContain('`failureTextActions[]`：把某个非 JSON 文本入口继续映射到稳定恢复动作分组')
    expect(publicJsonSchemaDoc).toContain('同一个 `textEntryPoint` 可以合法出现多条记录')
    expect(publicJsonSchemaDoc).toContain('`successTextEntries[]`')
    expect(publicJsonSchemaDoc).toContain('`referenceReadiness` 在非 JSON 文本模式下优先对应 `reference-stats-summary`')
    expect(publicJsonSchemaDoc).toContain('`summary.platformStats` 当前优先对应 `platform-summary`')
    expect(publicJsonSchemaDoc).toContain('`summary.referenceStats` 当前优先对应 `reference-stats-summary`')
    expect(publicJsonSchemaDoc).toContain('`summary.executabilityStats` 当前优先对应 `executability-stats-summary`')
    expect(publicJsonSchemaDoc).toContain('`use` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(publicJsonSchemaDoc).toContain('`use` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(publicJsonSchemaDoc).toContain('`use` 的 `preview` 当前优先对应 `preview-detail`')
    expect(publicJsonSchemaDoc).toContain('`rollback` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(publicJsonSchemaDoc).toContain('`rollback` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(publicJsonSchemaDoc).toContain('`import apply` 成功态里的 `platformSummary` 当前优先对应 `platform-summary`')
    expect(publicJsonSchemaDoc).toContain('`import apply` 的 `scopeAvailability` 当前优先对应 `scope-availability`')
    expect(publicJsonSchemaDoc).toContain('`import apply` 的 `preview` 当前优先对应 `preview-detail`')
    expect(publicJsonSchemaDoc).toContain('如果你想把这层 contract 直接收口成“失败恢复消费模板”')
    expect(publicJsonSchemaDoc).toContain('const failureTemplate = {')
    expect(publicJsonSchemaDoc).toContain('byTextEntryPoint: new Map<string, string[]>()')
    expect(publicJsonSchemaDoc).toContain('先用 `failureCodes[].textEntryPoint` 找“该看哪段文本”')
    expect(readme).toContain('`use` 是最完整的参考面')
    expect(readme).toContain('const useAction = schema.data.commandCatalog.actions.find(')
    expect(readme).toContain("code: useFailureByCode.get('CONFIRMATION_REQUIRED')")
    expect(readme).toContain('actionsFromRiskSummary')
    expect(publicJsonSchemaDoc).toContain('`use` 是最完整的参考面')
    expect(publicJsonSchemaDoc).toContain('const useAction = schema.data.commandCatalog.actions.find(')
    expect(publicJsonSchemaDoc).toContain("code: useFailureByCode.get('CONFIRMATION_REQUIRED')")
    expect(publicJsonSchemaDoc).toContain('actionsFromRiskSummary')
    expect(publicJsonSchemaDoc).toContain('fieldPresence')
    expect(publicJsonSchemaDoc).toContain('fieldSources')
    expect(publicJsonSchemaDoc).toContain('fieldStability')
    expect(publicJsonSchemaDoc).toContain('`command-service`')
    expect(publicJsonSchemaDoc).toContain('`platform-adapter`')
    expect(publicJsonSchemaDoc).toContain('`summary.referenceStats`')
    expect(publicJsonSchemaDoc).toContain('`consumerProfiles`：这一整类 action 共享什么消费形状。')
    expect(publicJsonSchemaDoc).toContain("consumerProfileIds?: Array<'single-platform-write' | 'readonly-import-batch' | 'readonly-state-audit'>")
    expect(publicJsonSchemaDoc).toContain('`readonly-state-audit` 统一 `current / list / validate / export` 这条只读状态审计面')
    expect(publicJsonSchemaDoc).toContain('`readonly-import-batch` 统一 `import / import preview` 这条只读批量导入分析面')
    expect(publicJsonSchemaDoc).toContain('`sharedItemFields`：这一整类 action 的 item 级优先字段。')
    expect(publicJsonSchemaDoc).toContain('`optionalItemFields`：不同 action 可能额外补充的 item 级 explainable。')
    expect(publicJsonSchemaDoc).toContain('`sharedFailureFields`：这一整类 action 的失败态优先字段。')
    expect(publicJsonSchemaDoc).toContain('`optionalFailureFields`：不同 action 可能额外补充的失败态 explainable。')
    expect(publicJsonSchemaDoc).toContain('`starterTemplate`：只读画像的最小机器消费模板')
    expect(publicJsonSchemaDoc).toContain('`starterRecipes`：画像级最小命令跳转 recipe')
    expect(publicJsonSchemaDoc).toContain('`exampleActions`：这一类画像有哪些代表命令。')
    expect(publicJsonSchemaDoc).toContain('`bestEntryAction`：第一次接入这类画像时优先参考哪个 action。')
    expect(publicJsonSchemaDoc).toContain('`defaultConsumerActionId / defaultCommandExample / defaultCommandPurpose`')
    expect(publicJsonSchemaDoc).toContain('`summarySectionGuidance`：这一类画像里的 summary section 适合拿来做 overview、governance、gating 还是 routing。')
    expect(publicJsonSchemaDoc).toContain('`followUpHints`：看完 summary 之后，下一步更适合展开哪些字段，或者走哪种处理动作。')
    expect(publicJsonSchemaDoc).toContain('`triageBuckets`：把 summary 和 item explainable 进一步归成稳定分流桶')
    expect(publicJsonSchemaDoc).toContain('运行时 `summary.triageStats` 会把这些分流桶实例化成当前批次的真实计数')
    expect(publicJsonSchemaDoc).toContain('`consumerActions`：把 `summarySections / triageBuckets / followUpHints` 收口成可直接消费的动作目录')
    expect(publicJsonSchemaDoc).toContain('`recommendedActions`：公开全局稳定动作词表')
    expect(publicJsonSchemaDoc).toContain('如果外部调用方想避免按 action 名字硬编码，可以先消费 `consumerProfiles[]`')
    expect(publicJsonSchemaDoc).toContain('再用 `sharedSummaryFields / sharedItemFields / sharedFailureFields` 构建稳定基础读取器')
    expect(publicJsonSchemaDoc).toContain('对于只读画像，还可以先读取 `defaultConsumerActionId / defaultCommandExample / defaultCommandPurpose`')
    expect(publicJsonSchemaDoc).toContain('再读取 `summarySectionGuidance[]`')
    expect(publicJsonSchemaDoc).toContain('再读取 `followUpHints[]`，直接知道 summary 看完之后下一步该展开哪些 detail 字段')
    expect(publicJsonSchemaDoc).toContain('如果需要更偏自动化的接入，再读取 `triageBuckets[]`，直接按稳定桶做分流')
    expect(publicJsonSchemaDoc).toContain('如果想直接拿一层已经拼好的动作目录，则直接读取 `consumerActions[]`')
    expect(publicJsonSchemaDoc).toContain('可以直接消费 `starterTemplate`')
    expect(publicJsonSchemaDoc).toContain('可以直接消费 `starterRecipes`')
    expect(publicJsonSchemaDoc).toContain('如果外部调用方只想先拿默认第一跳')
    expect(publicJsonSchemaDoc).toContain('actionId: profile?.defaultConsumerActionId')
    expect(publicJsonSchemaDoc).toContain('command: profile?.defaultCommandExample')
    expect(publicJsonSchemaDoc).toContain('purpose: profile?.defaultCommandPurpose')
    expect(publicJsonSchemaDoc).toContain('`readonly-import-batch-minimal-reader`')
    expect(publicJsonSchemaDoc).toContain('starterTemplate?.summary.fields')
    expect(publicJsonSchemaDoc).toContain('starterTemplate?.items.sharedFields')
    expect(publicJsonSchemaDoc).toContain('starterTemplate?.failure.fields')
    expect(publicJsonSchemaDoc).toContain('starterTemplate?.flow.defaultConsumerFlowId')
    expect(publicJsonSchemaDoc).toContain('profile?.starterRecipes ?? []')
    expect(publicJsonSchemaDoc).toContain('discover: recipe.discover')
    expect(publicJsonSchemaDoc).toContain('runtime: recipe.runtime')
    expect(publicJsonSchemaDoc).toContain('只读画像的最轻量入口现在可以理解为 `defaultCommandExample -> defaultConsumerFlowId -> consumerFlow[] -> consumerActions[] -> recommendedActions[]`')
    expect(publicJsonSchemaDoc).toContain('const defaultReadonlyConsumerPath = {')
    expect(publicJsonSchemaDoc).toContain('nextStepFamily: defaultRecommendedAction?.family')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --consumer-profile readonly-import-batch')
    expect(publicJsonSchemaDoc).toContain('未知 id 返回 `SCHEMA_CONSUMER_PROFILE_NOT_FOUND`')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --action import-apply')
    expect(publicJsonSchemaDoc).toContain('"action": "use"')
    expect(publicJsonSchemaDoc).toContain('"conditionCode": "WHEN_DRY_RUN_IS_REQUESTED"')
    expect(publicJsonSchemaDoc).toContain('"fields": ["dryRun", "changedFiles", "backupId"]')
    expect(publicJsonSchemaDoc).toContain('未知 action 返回 `SCHEMA_ACTION_NOT_FOUND`')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --recommended-action continue-to-write')
    expect(publicJsonSchemaDoc).toContain('"code": "continue-to-write"')
    expect(publicJsonSchemaDoc).toContain('"family": "execute"')
    expect(publicJsonSchemaDoc).toContain('"availability": ["readonly"]')
    expect(publicJsonSchemaDoc).toContain('继续进入后续写入链路')
    expect(publicJsonSchemaDoc).toContain('未知 code 返回 `SCHEMA_RECOMMENDED_ACTION_NOT_FOUND`')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --catalog-summary')
    expect(publicJsonSchemaDoc).toContain('`schema --json --catalog-summary` 是 schema catalog 的轻量目录模式')
    expect(publicJsonSchemaDoc).toContain('`data.catalogSummary`')
    expect(publicJsonSchemaDoc).toContain('`hasStarterTemplate`、`starterTemplateId` 与 `recommendedEntryMode`')
    expect(publicJsonSchemaDoc).toContain('`defaultConsumerActionId`、`defaultCommandExample`、`defaultCommandPurpose`')
    expect(publicJsonSchemaDoc).toContain('不再展开完整 `commandCatalog`、`schemaId` 或 `schema`')
    expect(publicJsonSchemaDoc).toContain('推荐的最小发现顺序可以固定为：先读取 `catalogSummary`')
    expect(publicJsonSchemaDoc).toContain('如果需要字段级 contract，再切到完整 `schema --json`')
    expect(publicJsonSchemaDoc).toContain('`schema --json --catalog-summary` 的最小成功样例：')
    expect(publicJsonSchemaDoc).toContain('"catalogSummary": {')
    expect(publicJsonSchemaDoc).toContain('"consumerProfiles": 3')
    expect(publicJsonSchemaDoc).toContain('"recommendedActions": 15')
    expect(publicJsonSchemaDoc).toContain('"id": "readonly-state-audit"')
    expect(publicJsonSchemaDoc).toContain('"bestEntryAction": "current"')
    expect(publicJsonSchemaDoc).toContain('"defaultConsumerActionId": "inspect-overview"')
    expect(publicJsonSchemaDoc).toContain('"defaultCommandExample": "api-switcher current --json"')
    expect(publicJsonSchemaDoc).toContain('"recommendedEntryMode": "starter-template"')
    expect(publicJsonSchemaDoc).toContain('"hasStarterTemplate": true')
    expect(publicJsonSchemaDoc).toContain('"starterTemplateId": "readonly-state-audit-minimal-reader"')
    expect(publicJsonSchemaDoc).toContain('文本模式下，`schema --catalog-summary` 会使用同一份 `catalogSummary.consumerProfiles[]` 输出推荐入口提示')
    expect(publicJsonSchemaDoc).toContain('Catalog Summary:')
    expect(publicJsonSchemaDoc).toContain('recommended=starter-template')
    expect(publicJsonSchemaDoc).toContain('recommended=full-consumer-profile')
    expect(publicJsonSchemaDoc).toContain('defaultAction=inspect-overview')
    expect(publicJsonSchemaDoc).toContain('command=api-switcher current --json')
    expect(publicJsonSchemaDoc).toContain('next=api-switcher schema --json --consumer-profile readonly-state-audit')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --action preview')
    expect(publicJsonSchemaDoc).toContain('api-switcher schema --json --recommended-action continue-to-write')
    expect(publicJsonSchemaDoc).toContain('catalog-summary -> action -> recommended-action -> runtime payload')
    expect(publicJsonSchemaDoc).toContain('"recipeId": "single-platform-write-preview-to-execute"')
    expect(publicJsonSchemaDoc).toContain('"discover": "api-switcher schema --json --catalog-summary"')
    expect(publicJsonSchemaDoc).toContain('"runtime": "api-switcher preview <selector> --json"')
    expect(publicJsonSchemaDoc).toContain('"code": "continue-to-write"')
    expect(publicJsonSchemaDoc).toContain('catalogSummary?: {')
    expect(publicJsonSchemaDoc).toContain('hasStarterTemplate?: boolean')
    expect(publicJsonSchemaDoc).toContain("starterTemplateId?: 'readonly-state-audit-minimal-reader' | 'readonly-import-batch-minimal-reader'")
    expect(publicJsonSchemaDoc).toContain("recommendedEntryMode?: 'starter-template' | 'full-consumer-profile'")
    expect(publicJsonSchemaDoc).toContain('consumerActions: profile?.consumerActions ?? []')
    expect(publicJsonSchemaDoc).toContain('recommendedActions: schema.data.commandCatalog.recommendedActions ?? []')
    expect(publicJsonSchemaDoc).toContain("item.id === 'readonly-import-batch'")
    expect(publicJsonSchemaDoc).toContain('`summary.secretExportPolicy`')
    expect(publicJsonSchemaDoc).toContain('`profiles[].secretExportSummary`')
    expect(publicJsonSchemaDoc).toContain('`error.details.referenceGovernance.primaryReason/reasonCodes`')
    expect(publicJsonSchemaDoc).toContain('`error.details.referenceGovernance.referenceDetails[]`')
    expect(publicJsonSchemaDoc).toContain('referenceGovernanceCodes?:')
    expect(publicJsonSchemaDoc).toContain('`REFERENCE_INPUT_CONFLICT`')
    expect(publicJsonSchemaDoc).toContain('`INLINE_SECRET_PRESENT`')
    expect(publicJsonSchemaDoc).toContain('失败态不要读取或等待 `summary.referenceStats`')
    expect(publicJsonSchemaDoc).toContain('WHEN_REFERENCE_GOVERNANCE_FAILURE_IS_DETECTED')
    expect(publicJsonSchemaDoc).toContain('`always` / `conditional`')
    expect(publicJsonSchemaDoc).toContain('`stable`')
    expect(publicJsonSchemaDoc).toContain('`bounded`')
    expect(publicJsonSchemaDoc).toContain('`expandable`')
    expect(publicJsonSchemaDoc).toContain('WHEN_SCOPE_AVAILABILITY_IS_RESOLVED')
    expect(publicJsonSchemaDoc).toContain('readOrderGroups')
    expect(publicJsonSchemaDoc).toContain('`summary` -> `selection` -> `items` -> `detail` -> `artifacts`')
    expect(publicJsonSchemaDoc).toContain('`error-core` -> `error-details` -> `error-recovery`')
    expect(publicJsonSchemaDoc).toContain('`error.code`，再读 `error.details.referenceGovernance.primaryReason/reasonCodes`')
    expect(publicJsonSchemaDoc).toContain('再按需展开 `error.details.referenceGovernance.referenceDetails[]`')
    expect(readme).toContain('"semantic": "platform-aggregate"')
    expect(readme).toContain('"semantic": "error-core"')
    expect(readme).toContain('"$schema": "https://json-schema.org/draft/2020-12/schema"')
    expect(readme).toContain(`"$id": "${machineReadableSchema.$id}"`)
    expect(readme).toContain('<redacted:inline-secret>')
    expect(publicJsonSchemaDoc).toContain('<redacted:inline-secret>')
  })

  it('README 保留 schema --schema-version --json 轻量返回示例，避免版本探测 contract 漂移', () => {
    expect(readme).toContain('api-switcher schema --schema-version --json')
    expect(readme).toContain('"ok": true')
    expect(readme).toContain('"action": "schema"')
    expect(readme).toContain(`"schemaVersion": "${PUBLIC_JSON_SCHEMA_VERSION}"`)
    expect(readme).toContain('"data": {')
  })
})
